# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_logo', models.CharField(max_length=100)),
                ('template_title', models.CharField(max_length=100)),
            ],
        ),
    ]
