# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='Sample',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='template_logo',
            new_name='sample_logo',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='template_title',
            new_name='sample_title',
        ),
    ]
