# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20171126_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
